import { images } from './images';

// TODO add the localization for each language
// !change to correct slug for each translation to be same as english
export const services = {
	english: [
		{
			id: 'service-1',
			title: 'Tour Packages',
			slug: 'tour-packages',
			description: 'Explore curated tours covering the best destinations and experiences.',
			icon: images.tourGuide,
			content:
				"Explore curated tours that highlight the best of Albania. From breathtaking natural wonders to cultural landmarks, our tour packages are tailored to provide unforgettable experiences for all types of travelers. Whether you're an adventure seeker, a history enthusiast, or someone who loves relaxing by the beach, we’ve got something special for you.",
			whyUsTitle: 'Why Choose Us:',
			whyUsArr: ['Expertly crafted itineraries', 'Knowledgeable local tour guides', 'Flexible options for families, couples, and solo travelers'],
			cta: '..more tours',
			cta2: 'Explore More Tours',
		},
		{
			id: 'service-2',
			title: 'Transfer Services',
			slug: 'city-transfer',
			description: 'Reliable and comfortable city transfers to meet all your travel needs.',
			icon: images.transfer,
			content:
				'Enjoy reliable and comfortable city transfers during your Albanian adventure. Our transfer services ensure you travel with ease, whether it’s airport pickups, intercity journeys, or custom routes. We prioritize safety and punctuality, so you can focus on exploring.',
			whyUsTitle: 'Our Transfer Services Include:',
			whyUsArr: ['Airport to city transfers', 'Intercity connections', 'Private and group options'],
			cta: '...more transfers',
			cta2: 'Discover More Transfers',
		},
		{
			id: 'service-3',
			title: 'Medical Tourism',
			slug: 'medical-tourism',
			description: 'Access top healthcare services while exploring new destinations.',
			icon: images.medicalTourism,
			content:
				'Combine top-notch healthcare services with the beauty of Albania. Our medical tourism packages connect you with leading healthcare providers while giving you the chance to explore our beautiful country. From wellness retreats to specialized treatments, Albania is an ideal destination for health and relaxation.',
			whyUsTitle: 'Benefits of Medical Tourism in Albania:',
			whyUsArr: ['Access to affordable, high-quality medical care', 'Recover in serene and picturesque settings', 'Personalized support throughout your stay'],
			cta: '..act now!',
			cta2: 'Act Now for Medical Tourism',
		},
		{
			id: 'service-4',
			title: 'Hotel Reservation',
			slug: 'hotel-reservation',
			description: 'Book your stay at top-rated hotels tailored to your preferences.',
			icon: images.reservation,
			content:
				'Find and book your ideal stay at top-rated hotels in Albania. Whether you prefer luxurious accommodations or cozy boutique hotels, we ensure your comfort and satisfaction. Our reservation services are tailored to match your preferences and budget.',
			whyUsTitle: 'Why Book With Us:',
			whyUsArr: ['Access to exclusive deals', 'Personalized recommendations', 'Quick and hassle-free bookings'],
			cta: '...book now!',
			cta2: 'Book Your Hotel Now',
		},
		{
			id: 'service-5',
			title: 'Rent A Car',
			slug: 'rent-car',
			description: 'Convenient and affordable car rental services for your travels.',
			icon: images.rentalCar,
			content:
				'Explore Albania at your own pace with our convenient and affordable car rental services. From city drives to countryside adventures, our fleet of reliable vehicles ensures a smooth journey wherever you go.',
			whyUsTitle: 'Why Rent A Car From Us:',
			whyUsArr: ['Wide range of vehicle options', 'Affordable rates', 'Easy pick-up and drop-off locations'],
			cta: '...rent now!',
			cta2: 'Rent Your Car Today',
		},
	],
	deutsch: [
		{
			id: 'service-1',
			title: 'Reisepakete',
			slug: 'reisepakete',
			description: 'Erkunden Sie kuratierte Touren zu den besten Reisezielen und Erlebnissen.',
			icon: images.tourGuide,
			content:
				'Erkunden Sie kuratierte Touren, die die besten Seiten Albaniens hervorheben. Von atemberaubenden Naturwundern bis hin zu kulturellen Sehenswürdigkeiten – unsere Reisepakete bieten unvergessliche Erlebnisse für alle Arten von Reisenden. Egal, ob Sie ein Abenteurer, Geschichtsinteressierter oder Strandliebhaber sind, wir haben etwas Besonderes für Sie.',
			whyUsTitle: 'Warum uns wählen:',
			whyUsArr: ['Fachmännisch gestaltete Reiserouten', 'Erfahrene lokale Reiseleiter', 'Flexible Optionen für Familien, Paare und Alleinreisende'],
			cta: '..mehr Touren',
			cta2: 'Mehr Touren entdecken',
		},
		{
			id: 'service-2',
			title: 'Transferdienste',
			slug: 'stadt-transfer',
			description: 'Zuverlässige und komfortable Transfers, um alle Ihre Reisebedürfnisse zu erfüllen.',
			icon: images.transfer,
			content:
				'Genießen Sie zuverlässige und komfortable Transfers während Ihres Albanien-Abenteuers. Unsere Transferdienste sorgen für eine problemlose Reise, sei es für Flughafentransfers, Fahrten zwischen Städten oder individuelle Routen. Wir legen Wert auf Sicherheit und Pünktlichkeit, damit Sie sich ganz auf Ihre Erkundung konzentrieren können.',
			whyUsTitle: 'Unsere Transferdienste umfassen:',
			whyUsArr: ['Flughafentransfers', 'Verbindungen zwischen Städten', 'Private und Gruppenoptionen'],
			cta: '...mehr Transfers',
			cta2: 'Weitere Transfers entdecken',
		},
		{
			id: 'service-3',
			title: 'Medizintourismus',
			slug: 'medizintourismus',
			description: 'Greifen Sie auf erstklassige Gesundheitsdienstleistungen zu, während Sie neue Reiseziele erkunden.',
			icon: images.medicalTourism,
			content:
				'Kombinieren Sie erstklassige Gesundheitsdienstleistungen mit der Schönheit Albaniens. Unsere Medizintourismus-Pakete verbinden Sie mit führenden Gesundheitsanbietern und bieten Ihnen gleichzeitig die Möglichkeit, unser wunderschönes Land zu entdecken. Von Wellness-Retreats bis hin zu spezialisierten Behandlungen – Albanien ist ein ideales Ziel für Gesundheit und Erholung.',
			whyUsTitle: 'Vorteile des Medizintourismus in Albanien:',
			whyUsArr: [
				'Zugang zu erschwinglicher, hochwertiger medizinischer Versorgung',
				'Erholung in ruhigen und malerischen Umgebungen',
				'Individuelle Betreuung während Ihres Aufenthalts',
			],
			cta: '..jetzt handeln!',
			cta2: 'Jetzt für Medizintourismus handeln',
		},
		{
			id: 'service-4',
			title: 'Hotelreservierung',
			slug: 'hotelreservierung',
			description: 'Buchen Sie Ihren Aufenthalt in erstklassigen Hotels, die auf Ihre Wünsche zugeschnitten sind.',
			icon: images.reservation,
			content:
				'Finden und buchen Sie Ihren idealen Aufenthalt in erstklassigen Hotels in Albanien. Ob luxuriöse Unterkünfte oder gemütliche Boutique-Hotels – wir sorgen für Ihren Komfort und Ihre Zufriedenheit. Unsere Reservierungsdienste sind darauf ausgelegt, Ihre Wünsche und Ihr Budget zu erfüllen.',
			whyUsTitle: 'Warum bei uns buchen:',
			whyUsArr: ['Zugang zu exklusiven Angeboten', 'Individuelle Empfehlungen', 'Schnelle und unkomplizierte Buchungen'],
			cta: '...jetzt buchen!',
			cta2: 'Buchen Sie jetzt Ihr Hotel',
		},
		{
			id: 'service-5',
			title: 'Auto mieten',
			slug: 'auto-mieten',
			description: 'Bequeme und erschwingliche Autovermietung für Ihre Reisen.',
			icon: images.rentalCar,
			content:
				'Entdecken Sie Albanien in Ihrem eigenen Tempo mit unseren bequemen und erschwinglichen Autovermietungsdiensten. Ob Stadtfahrten oder Abenteuer auf dem Land – unsere zuverlässige Fahrzeugflotte garantiert eine reibungslose Reise.',
			whyUsTitle: 'Warum ein Auto bei uns mieten:',
			whyUsArr: ['Große Auswahl an Fahrzeugoptionen', 'Erschwingliche Preise', 'Einfache Abhol- und Rückgabeorte'],
			cta: '...jetzt mieten!',
			cta2: 'Mieten Sie Ihr Auto heute',
		},
	],
	français: [
		{
			id: 'service-1',
			title: 'Forfaits Touristiques',
			slug: 'tour-packages',
			description: 'Découvrez des circuits organisés couvrant les meilleures destinations et expériences.',
			icon: images.tourGuide,
			content:
				"Découvrez des circuits organisés mettant en valeur le meilleur de l'Albanie. Des merveilles naturelles époustouflantes aux sites culturels, nos forfaits sont conçus pour offrir des expériences inoubliables à tous les types de voyageurs. Que vous soyez un aventurier, un passionné d’histoire ou que vous aimiez simplement vous détendre sur la plage, nous avons quelque chose de spécial pour vous.",
			whyUsTitle: 'Pourquoi nous choisir :',
			whyUsArr: ['Itinéraires soigneusement élaborés', 'Guides locaux compétents', 'Options flexibles pour les familles, couples et voyageurs solitaires'],
			cta: '..plus de circuits',
			cta2: 'Découvrez plus de circuits',
		},
		{
			id: 'service-2',
			title: 'Services de Transfert',
			slug: 'city-transfer',
			description: 'Transferts urbains fiables et confortables pour répondre à tous vos besoins de voyage.',
			icon: images.transfer,
			content:
				'Profitez de transferts urbains fiables et confortables pendant votre aventure albanaise. Nos services garantissent un voyage sans stress, que ce soit pour les transferts aéroport, les trajets interurbains ou les itinéraires personnalisés. Nous privilégions la sécurité et la ponctualité, afin que vous puissiez profiter pleinement de votre séjour.',
			whyUsTitle: 'Nos services de transfert incluent :',
			whyUsArr: ['Transferts aéroport-ville', 'Connexions interurbaines', 'Options privées et de groupe'],
			cta: '...plus de transferts',
			cta2: 'Découvrez plus de transferts',
		},
		{
			id: 'service-3',
			title: 'Tourisme Médical',
			slug: 'medical-tourism',
			description: 'Accédez aux meilleurs services de santé tout en explorant de nouvelles destinations.',
			icon: images.medicalTourism,
			content:
				"Alliez soins de santé de haute qualité et découverte de l'Albanie. Nos forfaits de tourisme médical vous connectent aux meilleurs prestataires de soins tout en vous offrant l’opportunité d’explorer notre magnifique pays. Des retraites bien-être aux traitements spécialisés, l'Albanie est une destination idéale pour la santé et la détente.",
			whyUsTitle: 'Les avantages du tourisme médical en Albanie :',
			whyUsArr: [
				'Accès à des soins médicaux de qualité à prix abordable',
				'Récupération dans un cadre paisible et pittoresque',
				'Accompagnement personnalisé tout au long de votre séjour',
			],
			cta: '..réservez maintenant !',
			cta2: 'Réservez votre séjour médical maintenant',
		},
		{
			id: 'service-4',
			title: 'Réservation d’Hôtel',
			slug: 'hotel-reservation',
			description: 'Réservez votre séjour dans les meilleurs hôtels adaptés à vos préférences.',
			icon: images.reservation,
			content:
				"Trouvez et réservez votre séjour idéal dans les meilleurs hôtels d'Albanie. Que vous préfériez des hébergements de luxe ou des hôtels-boutiques chaleureux, nous veillons à votre confort et satisfaction. Nos services de réservation sont adaptés à vos préférences et à votre budget.",
			whyUsTitle: 'Pourquoi réserver avec nous :',
			whyUsArr: ['Accès à des offres exclusives', 'Recommandations personnalisées', 'Réservations rapides et sans tracas'],
			cta: '...réservez maintenant !',
			cta2: 'Réservez votre hôtel dès maintenant',
		},
		{
			id: 'service-5',
			title: 'Location de Voiture',
			slug: 'rent-car',
			description: 'Services de location de voiture pratiques et abordables pour vos déplacements.',
			icon: images.rentalCar,
			content:
				"Explorez l'Albanie à votre rythme grâce à nos services de location de voiture pratiques et abordables. Que ce soit pour une escapade urbaine ou une aventure à la campagne, notre flotte de véhicules fiables vous garantit un voyage en toute tranquillité.",
			whyUsTitle: 'Pourquoi louer une voiture chez nous :',
			whyUsArr: ['Large choix de véhicules', 'Tarifs abordables', 'Points de retrait et de retour faciles'],
			cta: '...louez maintenant !',
			cta2: 'Louez votre voiture dès aujourd’hui',
		},
	],
	русский: [
		{
			id: 'service-1',
			title: 'Туристические пакеты',
			slug: 'tour-packages',
			description: 'Исследуйте тщательно подобранные туры, охватывающие лучшие направления и впечатления.',
			icon: images.tourGuide,
			content:
				'Откройте для себя тщательно подобранные туры, которые демонстрируют лучшее из Албании. От потрясающих природных чудес до культурных достопримечательностей — наши турпакеты разработаны для незабываемых впечатлений для всех типов путешественников. Будь вы искателем приключений, любителем истории или ценителем отдыха на пляже, у нас есть что-то особенное для вас.',
			whyUsTitle: 'Почему выбрать нас:',
			whyUsArr: ['Профессионально разработанные маршруты', 'Опытные местные гиды', 'Гибкие варианты для семей, пар и одиночных путешественников'],
			cta: '..больше туров',
			cta2: 'Исследуйте больше туров',
		},
		{
			id: 'service-2',
			title: 'Трансферные услуги',
			slug: 'city-transfer',
			description: 'Надежные и комфортные городские трансферы для всех ваших путешествий.',
			icon: images.transfer,
			content:
				'Наслаждайтесь надежными и комфортными городскими трансферами во время вашего путешествия по Албании. Наши услуги трансфера обеспечивают удобство передвижения — будь то трансфер из аэропорта, межгородские поездки или индивидуальные маршруты. Мы гарантируем безопасность и пунктуальность, чтобы вы могли сосредоточиться на своем отдыхе.',
			whyUsTitle: 'Наши трансферные услуги включают:',
			whyUsArr: ['Трансферы из аэропорта в город', 'Междугородние перевозки', 'Частные и групповые варианты'],
			cta: '...больше трансферов',
			cta2: 'Узнать больше о трансферах',
		},
		{
			id: 'service-3',
			title: 'Медицинский туризм',
			slug: 'medical-tourism',
			description: 'Получите качественные медицинские услуги во время путешествия.',
			icon: images.medicalTourism,
			content:
				'Совместите качественные медицинские услуги с путешествием по Албании. Наши пакеты медицинского туризма соединяют вас с ведущими медицинскими учреждениями и позволяют наслаждаться красотой нашей страны. От оздоровительных курортов до специализированного лечения — Албания является идеальным местом для здоровья и релаксации.',
			whyUsTitle: 'Преимущества медицинского туризма в Албании:',
			whyUsArr: [
				'Доступ к качественному медицинскому обслуживанию по доступным ценам',
				'Восстановление в живописных местах',
				'Персональная поддержка на протяжении всего пребывания',
			],
			cta: '..действуйте сейчас!',
			cta2: 'Запишитесь на медицинский туризм',
		},
		{
			id: 'service-4',
			title: 'Бронирование отелей',
			slug: 'hotel-reservation',
			description: 'Забронируйте проживание в лучших отелях, соответствующих вашим предпочтениям.',
			icon: images.reservation,
			content:
				'Найдите и забронируйте идеальное проживание в лучших отелях Албании. Предпочитаете ли вы роскошные номера или уютные бутик-отели, мы гарантируем комфорт и удовлетворение. Наши услуги бронирования соответствуют вашим предпочтениям и бюджету.',
			whyUsTitle: 'Почему бронировать у нас:',
			whyUsArr: ['Доступ к эксклюзивным предложениям', 'Персонализированные рекомендации', 'Быстрое и удобное бронирование'],
			cta: '...забронировать сейчас!',
			cta2: 'Забронируйте отель сейчас',
		},
		{
			id: 'service-5',
			title: 'Аренда автомобилей',
			slug: 'rent-car',
			description: 'Удобные и доступные услуги аренды автомобилей для вашего путешествия.',
			icon: images.rentalCar,
			content:
				'Исследуйте Албанию в своем темпе с помощью удобных и доступных услуг аренды автомобилей. Будь то поездка по городу или загородное приключение, наш парк надежных автомобилей обеспечит комфортное путешествие куда бы вы ни направились.',
			whyUsTitle: 'Почему арендовать автомобиль у нас:',
			whyUsArr: ['Широкий выбор автомобилей', 'Доступные цены', 'Удобные места для получения и возврата авто'],
			cta: '...арендовать сейчас!',
			cta2: 'Арендуйте автомобиль сегодня',
		},
	],
	türkçe: [
		{
			id: 'service-1',
			title: 'Tur Paketleri',
			slug: 'tour-packages',
			description: 'En iyi destinasyonları ve deneyimleri kapsayan özenle seçilmiş turları keşfedin.',
			icon: images.tourGuide,
			content:
				"Arnavutluk'un en iyi yerlerini keşfetmek için özel olarak hazırlanmış turlara katılın. Muhteşem doğal güzelliklerden kültürel miraslara kadar her gezgin için unutulmaz deneyimler sunuyoruz. Macera severlerden tarih tutkunlarına, sahilde rahatlamayı sevenlere kadar herkes için özel bir turumuz var.",
			whyUsTitle: 'Neden Bizi Seçmelisiniz:',
			whyUsArr: ['Uzmanlar tarafından hazırlanmış güzergahlar', 'Bilgili yerel rehberler', 'Aileler, çiftler ve solo gezginler için esnek seçenekler'],
			cta: '..daha fazla tur',
			cta2: 'Daha Fazla Tur Keşfedin',
		},
		{
			id: 'service-2',
			title: 'Transfer Hizmetleri',
			slug: 'city-transfer',
			description: 'Tüm seyahat ihtiyaçlarınıza uygun güvenilir ve konforlu şehir içi transferler.',
			icon: images.transfer,
			content:
				'Arnavutluk seyahatinizde güvenilir ve konforlu transfer hizmetlerimizden yararlanın. Havaalanı karşılamalarından şehirler arası yolculuklara ve özel rotalara kadar her ihtiyacınıza uygun seçenekler sunuyoruz. Güvenlik ve dakikliği ön planda tutarak, seyahatinizin keyfini çıkarmanıza yardımcı oluyoruz.',
			whyUsTitle: 'Transfer Hizmetlerimiz Şunları İçerir:',
			whyUsArr: ['Havaalanı-şehir transferleri', 'Şehirler arası bağlantılar', 'Özel ve grup transfer seçenekleri'],
			cta: '...daha fazla transfer',
			cta2: 'Daha Fazla Transfer Keşfedin',
		},
		{
			id: 'service-3',
			title: 'Medikal Turizm',
			slug: 'medical-tourism',
			description: 'Yeni yerler keşfederken en iyi sağlık hizmetlerine erişin.',
			icon: images.medicalTourism,
			content:
				'Arnavutluk’un güzelliklerini keşfederken kaliteli sağlık hizmetlerinden de yararlanın. Medikal turizm paketlerimiz, önde gelen sağlık sağlayıcıları ile sizi buluştururken, aynı zamanda ülkemizin büyüleyici doğasını ve kültürel zenginliklerini keşfetme fırsatı sunar. Sağlık ve huzuru bir arada yaşamak için mükemmel bir destinasyon!',
			whyUsTitle: 'Arnavutluk’ta Medikal Turizmin Avantajları:',
			whyUsArr: ['Uygun fiyatlı, yüksek kaliteli sağlık hizmetleri', 'Huzurlu ve doğal ortamda iyileşme', 'Konaklamanız boyunca kişiselleştirilmiş destek'],
			cta: '..hemen harekete geç!',
			cta2: 'Medikal Turizm İçin Hemen Harekete Geçin',
		},
		{
			id: 'service-4',
			title: 'Otel Rezervasyonu',
			slug: 'hotel-reservation',
			description: 'Tercihlerinize uygun en iyi otellerde konaklama rezervasyonu yapın.',
			icon: images.reservation,
			content:
				'Arnavutluk’taki en iyi otellerde konforlu ve keyifli bir konaklama deneyimi yaşayın. Lüks otellerden butik otellere kadar geniş seçenekler sunuyoruz. Rezervasyon hizmetlerimiz, bütçenize ve isteklerinize en uygun konaklamayı bulmanızı sağlar.',
			whyUsTitle: 'Neden Bizimle Rezervasyon Yapmalısınız:',
			whyUsArr: ['Özel indirimlere erişim', 'Kişiselleştirilmiş otel önerileri', 'Hızlı ve sorunsuz rezervasyon süreci'],
			cta: '...hemen rezervasyon yap!',
			cta2: 'Otelinizi Şimdi Rezerve Edin',
		},
		{
			id: 'service-5',
			title: 'Araç Kiralama',
			slug: 'rent-car',
			description: 'Seyahatleriniz için pratik ve uygun fiyatlı araç kiralama hizmetleri.',
			icon: images.rentalCar,
			content:
				'Arnavutluk’u kendi hızınızda keşfetmek için pratik ve uygun fiyatlı araç kiralama hizmetimizden yararlanın. Şehir gezilerinden doğa kaçamaklarına kadar her türlü seyahatiniz için güvenilir araç seçenekleri sunuyoruz.',
			whyUsTitle: 'Neden Bizden Araç Kiralamalısınız:',
			whyUsArr: ['Geniş araç seçenekleri', 'Uygun fiyatlar', 'Kolay teslim alma ve bırakma noktaları'],
			cta: '...hemen kirala!',
			cta2: 'Aracınızı Bugün Kiralayın',
		},
	],
	italiano: [
		{
			id: 'service-1',
			title: 'Pacchetti Tour',
			slug: 'tour-packages',
			description: 'Esplora tour curati che coprono le migliori destinazioni e esperienze.',
			icon: images.tourGuide,
			content:
				"Esplora tour curati che evidenziano il meglio dell'Albania. Dalle meraviglie naturali mozzafiato ai luoghi culturali, i nostri pacchetti tour sono progettati per offrire esperienze indimenticabili per tutti i tipi di viaggiatori. Che tu sia un cercatore di avventure, un appassionato di storia o qualcuno che ama rilassarsi in spiaggia, abbiamo qualcosa di speciale per te.",
			whyUsTitle: 'Perché Scegliere Noi:',
			whyUsArr: ['Itinerari sapientemente progettati', 'Guide turistiche locali esperte', 'Opzioni flessibili per famiglie, coppie e viaggiatori singoli'],
			cta: '..altri tour',
			cta2: 'Esplora Altri Tour',
		},
		{
			id: 'service-2',
			title: 'Servizi di Trasferimento',
			slug: 'city-transfer',
			description: 'Trasferimenti in città affidabili e confortevoli per soddisfare tutte le tue esigenze di viaggio.',
			icon: images.transfer,
			content:
				'Goditi trasferimenti in città affidabili e confortevoli durante la tua avventura albanese. I nostri servizi di trasferimento garantiscono che tu possa viaggiare con facilità, sia che si tratti di prelievi in aeroporto, viaggi interurbani o percorsi personalizzati. Diamo priorità alla sicurezza e alla puntualità, così puoi concentrarti sull’esplorazione.',
			whyUsTitle: 'I Nostri Servizi di Trasferimento Includono:',
			whyUsArr: ['Trasferimenti da aeroporto a città', 'Collegamenti interurbani', 'Opzioni private e di gruppo'],
			cta: '...altri trasferimenti',
			cta2: 'Scopri Altri Trasferimenti',
		},
		{
			id: 'service-3',
			title: 'Turismo Medico',
			slug: 'medical-tourism',
			description: 'Accedi ai migliori servizi sanitari mentre esplori nuove destinazioni.',
			icon: images.medicalTourism,
			content:
				"Combina servizi sanitari di alta qualità con la bellezza dell'Albania. I nostri pacchetti di turismo medico ti mettono in contatto con fornitori di assistenza sanitaria leader, offrendoti al contempo l'opportunità di esplorare il nostro splendido paese. Dai ritiri benessere a trattamenti specializzati, l'Albania è una destinazione ideale per la salute e il relax.",
			whyUsTitle: 'Vantaggi del Turismo Medico in Albania:',
			whyUsArr: [
				'Accesso a cure mediche di alta qualità e a prezzi accessibili',
				'Recupero in ambienti sereni e pittoreschi',
				'Supporto personalizzato durante il tuo soggiorno',
			],
			cta: '..agisci ora!',
			cta2: 'Agisci Ora per il Turismo Medico',
		},
		{
			id: 'service-4',
			title: 'Prenotazione Hotel',
			slug: 'hotel-reservation',
			description: 'Prenota il tuo soggiorno in hotel con le migliori valutazioni in base alle tue preferenze.',
			icon: images.reservation,
			content:
				'Trova e prenota il tuo soggiorno ideale in hotel con le migliori valutazioni in Albania. Che tu preferisca sistemazioni di lusso o accoglienti boutique hotel, garantiamo il tuo comfort e soddisfazione. I nostri servizi di prenotazione sono progettati per soddisfare le tue preferenze e il tuo budget.',
			whyUsTitle: 'Perché Prenotare Con Noi:',
			whyUsArr: ['Accesso a offerte esclusive', 'Raccomandazioni personalizzate', 'Prenotazioni rapide e senza problemi'],
			cta: '...prenota ora!',
			cta2: 'Prenota il Tuo Hotel Ora',
		},
		{
			id: 'service-5',
			title: 'Noleggio Auto',
			slug: 'rent-car',
			description: 'Servizi di noleggio auto convenienti e accessibili per i tuoi viaggi.',
			icon: images.rentalCar,
			content:
				'Esplora l’Albania al tuo ritmo con i nostri servizi di noleggio auto convenienti e accessibili. Dai viaggi in città alle avventure in campagna, la nostra flotta di veicoli affidabili garantisce un viaggio fluido ovunque tu vada.',
			whyUsTitle: 'Perché Noleggiare un’Auto da Noi:',
			whyUsArr: ['Ampia gamma di opzioni di veicoli', 'Tariffe accessibili', 'Facili punti di ritiro e riconsegna'],
			cta: '...noleggia ora!',
			cta2: 'Noleggia la Tua Auto Oggi',
		},
	],
	español: [
		{
			id: 'service-1',
			title: 'Paquetes de Tour',
			slug: 'tour-packages',
			description: 'Explora tours curados que cubren los mejores destinos y experiencias.',
			icon: images.tourGuide,
			content:
				'Explora tours curados que destacan lo mejor de Albania. Desde impresionantes maravillas naturales hasta hitos culturales, nuestros paquetes de tour están diseñados para ofrecer experiencias inolvidables para todo tipo de viajeros. Ya sea que busques aventura, seas un entusiasta de la historia, o alguien que ama relajarse en la playa, tenemos algo especial para ti.',
			whyUsTitle: 'Por Qué Elegirnos:',
			whyUsArr: ['Itinerarios elaborados con experiencia', 'Guías locales conocedoras', 'Opciones flexibles para familias, parejas y viajeros solitarios'],
			cta: '..más tours',
			cta2: 'Explora Más Tours',
		},
		{
			id: 'service-2',
			title: 'Servicios de Transferencia',
			slug: 'city-transfer',
			description: 'Transferencias de ciudad confiables y cómodas para satisfacer todas tus necesidades de viaje.',
			icon: images.transfer,
			content:
				'Disfruta de transferencias de ciudad confiables y cómodas durante tu aventura en Albania. Nuestros servicios de transferencia aseguran que viajes con facilidad, ya sea recogidas en el aeropuerto, viajes entre ciudades o rutas personalizadas. Priorizamos la seguridad y la puntualidad, para que puedas concentrarte en explorar.',
			whyUsTitle: 'Nuestros Servicios de Transferencia Incluyen:',
			whyUsArr: ['Transferencias del aeropuerto a la ciudad', 'Conexiones entre ciudades', 'Opciones privadas y grupales'],
			cta: '...más transferencias',
			cta2: 'Descubre Más Transferencias',
		},
		{
			id: 'service-3',
			title: 'Turismo Médico',
			slug: 'medical-tourism',
			description: 'Accede a los mejores servicios de salud mientras exploras nuevos destinos.',
			icon: images.medicalTourism,
			content:
				'Combina servicios de salud de primer nivel con la belleza de Albania. Nuestros paquetes de turismo médico te conectan con proveedores de salud líderes mientras te dan la oportunidad de explorar nuestro hermoso país. Desde retiros de bienestar hasta tratamientos especializados, Albania es un destino ideal para la salud y la relajación.',
			whyUsTitle: 'Beneficios del Turismo Médico en Albania:',
			whyUsArr: [
				'Acceso a atención médica asequible y de alta calidad',
				'Recuperación en entornos serenos y pintorescos',
				'Apoyo personalizado durante tu estancia',
			],
			cta: '..¡actúa ahora!',
			cta2: 'Actúa Ahora para el Turismo Médico',
		},
		{
			id: 'service-4',
			title: 'Reserva de Hotel',
			slug: 'hotel-reservation',
			description: 'Reserva tu estancia en hoteles de alta calificación adaptados a tus preferencias.',
			icon: images.reservation,
			content:
				'Encuentra y reserva tu estancia ideal en hoteles de alta calificación en Albania. Ya sea que prefieras alojamientos lujosos o acogedores hoteles boutique, aseguramos tu comodidad y satisfacción. Nuestros servicios de reserva están diseñados para coincidir con tus preferencias y presupuesto.',
			whyUsTitle: 'Por Qué Reservar Con Nosotros:',
			whyUsArr: ['Acceso a ofertas exclusivas', 'Recomendaciones personalizadas', 'Reservas rápidas y sin complicaciones'],
			cta: '...¡reserva ahora!',
			cta2: 'Reserva Tu Hotel Ahora',
		},
		{
			id: 'service-5',
			title: 'Alquilar un Auto',
			slug: 'rent-car',
			description: 'Servicios de alquiler de autos convenientes y asequibles para tus viajes.',
			icon: images.rentalCar,
			content:
				'Explora Albania a tu propio ritmo con nuestros servicios de alquiler de autos convenientes y asequibles. Desde paseos por la ciudad hasta aventuras en el campo, nuestra flota de vehículos confiables asegura un viaje sin problemas donde sea que vayas.',
			whyUsTitle: 'Por Qué Alquilar un Auto Con Nosotros:',
			whyUsArr: ['Amplia gama de opciones de vehículos', 'Precios asequibles', 'Lugares de recogida y entrega fáciles'],
			cta: '...¡alquila ahora!',
			cta2: 'Alquila Tu Auto Hoy',
		},
	],

	polski: [
		{
			id: 'service-1',
			title: 'Pakiety wycieczkowe',
			slug: 'tour-packages',
			description: 'Odkryj starannie przygotowane wycieczki obejmujące najlepsze miejsca i doświadczenia.',
			icon: images.tourGuide,
			content:
				'Odkryj starannie przygotowane wycieczki, które podkreślają to, co najlepsze w Albanii. Od zapierających dech w piersiach cudów natury po kulturowe zabytki, nasze pakiety wycieczkowe są dostosowane, aby zapewnić niezapomniane doświadczenia dla wszystkich typów podróżnych. Niezależnie od tego, czy jesteś poszukiwaczem przygód, entuzjastą historii, czy kimś, kto uwielbia relaksować się na plaży, mamy coś specjalnego dla Ciebie.',
			whyUsTitle: 'Dlaczego warto wybrać nas:',
			whyUsArr: ['Starannie opracowane itineraria', 'Znajomi lokalni przewodnicy', 'Elastyczne opcje dla rodzin, par i podróżnych solo'],
			cta: '..więcej wycieczek',
			cta2: 'Odkryj więcej wycieczek',
		},
		{
			id: 'service-2',
			title: 'Usługi transferowe',
			slug: 'city-transfer',
			description: 'Niezawodne i komfortowe transfery miejskie, które spełnią wszystkie Twoje potrzeby podróżnicze.',
			icon: images.transfer,
			content:
				'Ciesz się niezawodnymi i komfortowymi transferami miejskimi podczas swojej albańskiej przygody. Nasze usługi transferowe zapewniają łatwe podróżowanie, niezależnie od tego, czy chodzi o odbiory z lotniska, podróże między miastami czy dostosowane trasy. Priorytetem jest dla nas bezpieczeństwo i punktualność, abyś mógł skupić się na odkrywaniu.',
			whyUsTitle: 'Nasze usługi transferowe obejmują:',
			whyUsArr: ['Transfery z lotniska do miasta', 'Połączenia między miastami', 'Opcje prywatne i grupowe'],
			cta: '...więcej transferów',
			cta2: 'Odkryj więcej transferów',
		},
		{
			id: 'service-3',
			title: 'Turystyka medyczna',
			slug: 'medical-tourism',
			description: 'Dostęp do najlepszych usług medycznych podczas odkrywania nowych miejsc.',
			icon: images.medicalTourism,
			content:
				'Połącz usługi medyczne najwyższej jakości z pięknem Albanii. Nasze pakiety turystyki medycznej łączą Cię z wiodącymi dostawcami usług zdrowotnych, dając Ci jednocześnie szansę na odkrywanie naszego pięknego kraju. Od uzdrowisk po specjalistyczne zabiegi, Albania jest idealnym miejscem na zdrowie i relaks.',
			whyUsTitle: 'Korzyści z turystyki medycznej w Albanii:',
			whyUsArr: [
				'Dostęp do przystępnej, wysokiej jakości opieki medycznej',
				'Odzyskaj siły w spokojnych i malowniczych sceneriach',
				'Spersonalizowane wsparcie przez cały czas pobytu',
			],
			cta: '..działaj teraz!',
			cta2: 'Działaj teraz w turystyce medycznej',
		},
		{
			id: 'service-4',
			title: 'Rezerwacja hotelu',
			slug: 'hotel-reservation',
			description: 'Zarezerwuj swój pobyt w najwyżej ocenianych hotelach dostosowanych do Twoich preferencji.',
			icon: images.reservation,
			content:
				'Znajdź i zarezerwuj idealny pobyt w najwyżej ocenianych hotelach w Albanii. Niezależnie od tego, czy preferujesz luksusowe zakwaterowanie, czy przytulne hotele butikowe, zapewniamy Twój komfort i satysfakcję. Nasze usługi rezerwacyjne są dostosowane do Twoich preferencji i budżetu.',
			whyUsTitle: 'Dlaczego warto zarezerwować u nas:',
			whyUsArr: ['Dostęp do ekskluzywnych ofert', 'Spersonalizowane rekomendacje', 'Szybkie i bezproblemowe rezerwacje'],
			cta: '...zarezerwuj teraz!',
			cta2: 'Zarezerwuj swój hotel teraz',
		},
		{
			id: 'service-5',
			title: 'Wynajem samochodu',
			slug: 'rent-car',
			description: 'Wygodne i przystępne usługi wynajmu samochodów dla Twoich podróży.',
			icon: images.rentalCar,
			content:
				'Odkrywaj Albanię we własnym tempie dzięki naszym wygodnym i przystępnym usługom wynajmu samochodów. Od miejskich przejażdżek po przygody na wsi, nasza flota niezawodnych pojazdów zapewnia płynną podróż, gdziekolwiek się wybierzesz.',
			whyUsTitle: 'Dlaczego warto wynająć samochód u nas:',
			whyUsArr: ['Szeroki wybór pojazdów', 'Przystępne ceny', 'Łatwe miejsca odbioru i zwrotu'],
			cta: '...wynajmij teraz!',
			cta2: 'Wynajmij swój samochód dzisiaj',
		},
	],

	українська: [
		{
			id: 'service-1',
			title: 'Туристичні пакети',
			slug: 'tour-packages',
			description: 'Досліджуйте кураторські тури, що охоплюють найкращі напрямки та враження.',
			icon: images.tourGuide,
			content:
				"Досліджуйте кураторські тури, які підкреслюють найкраще з Албанії. Від захоплюючих природних чудес до культурних пам'яток, наші туристичні пакети призначені для того, щоб забезпечити незабутні враження для всіх типів мандрівників. Чи ви шукаєте пригод, чи ви ентузіаст історії, чи просто любите відпочивати на пляжі, у нас є щось особливе для вас.",
			whyUsTitle: 'Чому обрати нас:',
			whyUsArr: ['Експертно розроблені маршрути', 'Знаючі місцеві гіди', 'Гнучкі варіанти для сімей, пар та одиночних мандрівників'],
			cta: '..більше турів',
			cta2: 'Досліджуйте більше турів',
		},
		{
			id: 'service-2',
			title: 'Трансферні послуги',
			slug: 'city-transfer',
			description: 'Надійні та зручні міські трансфери для задоволення всіх ваших потреб у подорожах.',
			icon: images.transfer,
			content:
				'Скористайтеся надійними та комфортними міськими трансферами під час вашої албанської пригоди. Наші трансферні послуги забезпечують легкість подорожування, будь то трансфери з аеропорту, міжміські подорожі чи спеціальні маршрути. Ми пріоритетуємо безпеку та пунктуальність, щоб ви могли зосередитися на дослідженні.',
			whyUsTitle: 'Наші трансферні послуги включають:',
			whyUsArr: [`Трансфери з аеропорту до міста', 'Міжміські з'єднання', 'Приватні та групові варіанти`],
			cta: '...більше трансферів',
			cta2: 'Відкрийте більше трансферів',
		},
		{
			id: 'service-3',
			title: 'Медичний туризм',
			slug: 'medical-tourism',
			description: 'Отримайте доступ до найкращих медичних послуг, досліджуючи нові напрямки.',
			icon: images.medicalTourism,
			content: `Поєднайте найкращі медичні послуги з красою Албанії. Наші пакети медичного туризму з'єднують вас з провідними медичними закладами, одночасно надаючи вам можливість дослідити нашу прекрасну країну. Від відпочинків для оздоровлення до спеціалізованих процедур, Албанія є ідеальним місцем для здоров'я та релаксації.`,
			whyUsTitle: 'Переваги медичного туризму в Албанії:',
			whyUsArr: [
				'Доступ до доступної, високоякісної медичної допомоги',
				'Відновлення в спокійних та живописних умовах',
				'Індивідуальна підтримка протягом вашого перебування',
			],
			cta: '..дійте зараз!',
			cta2: 'Дійте зараз для медичного туризму',
		},
		{
			id: 'service-4',
			title: 'Резервування готелів',
			slug: 'hotel-reservation',
			description: 'Забронюйте своє перебування в найкращих готелях, відповідно до ваших уподобань.',
			icon: images.reservation,
			content:
				'Знайдіть та забронюйте своє ідеальне перебування в найкращих готелях в Албанії. Чи віддаєте перевагу розкішному проживанню, чи затишним бутік-готелям, ми забезпечимо ваш комфорт і задоволення. Наші послуги бронювання налаштовані відповідно до ваших уподобань і бюджету.',
			whyUsTitle: 'Чому бронювати з нами:',
			whyUsArr: ['Доступ до ексклюзивних пропозицій', 'Індивідуальні рекомендації', 'Швидке та безпроблемне бронювання'],
			cta: '...бронюйте зараз!',
			cta2: 'Забронюйте свій готель зараз',
		},
		{
			id: 'service-5',
			title: 'Оренда автомобіля',
			slug: 'rent-car',
			description: 'Зручні та доступні послуги оренди автомобілів для ваших подорожей.',
			icon: images.rentalCar,
			content:
				'Досліджуйте Албанію у власному ритмі з нашими зручними та доступними послугами оренди автомобілів. Від міських поїздок до пригод на селі, наш автопарк надійних автомобілів забезпечує безперебійну подорож, куди б ви не поїхали.',
			whyUsTitle: 'Чому орендувати автомобіль у нас:',
			whyUsArr: ['Широкий вибір автомобілів', 'Доступні ціни', 'Легкі пункти отримання та повернення'],
			cta: '...орендуйте зараз!',
			cta2: 'Орендуйте свій автомобіль сьогодні',
		},
	],
	nederlands: [
		{
			id: 'service-1',
			title: 'Rondreizen',
			slug: 'tour-packages',
			description: 'Verken samengestelde rondleidingen die de beste bestemmingen en ervaringen dekken.',
			icon: images.tourGuide,
			content:
				'Verken samengestelde rondleidingen die het beste van Albanië benadrukken. Van adembenemende natuurlijke wonderen tot culturele bezienswaardigheden, onze rondreis pakketten zijn ontworpen om onvergetelijke ervaringen te bieden voor alle soorten reizigers. Of je nu een avontuurlijke reiziger bent, een geschiedenisliefhebber of iemand die graag ontspannen aan het strand is, we hebben iets bijzonders voor jou.',
			whyUsTitle: 'Waarom voor ons kiezen:',
			whyUsArr: ['Vakkundig samengestelde reisroutes', 'Kennisrijke lokale gidsen', 'Flexibele opties voor gezinnen, stellen en solo reizigers'],
			cta: '..meer rondleidingen',
			cta2: 'Ontdek Meer Rondleidingen',
		},
		{
			id: 'service-2',
			title: 'Transferdiensten',
			slug: 'city-transfer',
			description: 'Betrouwbare en comfortabele stadsoverdrachten om aan al je reisbehoeften te voldoen.',
			icon: images.transfer,
			content:
				'Geniet van betrouwbare en comfortabele stadsoverdrachten tijdens je Albanese avontuur. Onze transferdiensten zorgen ervoor dat je gemakkelijk reist, of het nu gaat om luchthaventransfers, intercity reizen of aangepaste routes. We geven prioriteit aan veiligheid en stiptheid, zodat jij je kunt concentreren op het verkennen.',
			whyUsTitle: 'Onze transferdiensten omvatten:',
			whyUsArr: ['Luchthaven naar stadsoverdrachten', 'Intercity verbindingen', 'Privé- en groepsopties'],
			cta: '...meer transfers',
			cta2: 'Ontdek Meer Transfers',
		},
		{
			id: 'service-3',
			title: 'Medisch Toerisme',
			slug: 'medical-tourism',
			description: 'Toegang tot top gezondheidszorgdiensten terwijl je nieuwe bestemmingen verkent.',
			icon: images.medicalTourism,
			content:
				'Combineer eersteklas gezondheidszorgdiensten met de schoonheid van Albanië. Onze medische toerismepakketten verbinden je met toonaangevende zorgverleners terwijl je de kans krijgt om ons prachtige land te verkennen. Van wellness retraites tot gespecialiseerde behandelingen, Albanië is een ideale bestemming voor gezondheid en ontspanning.',
			whyUsTitle: 'Voordelen van medisch toerisme in Albanië:',
			whyUsArr: [
				'Toegang tot betaalbare, hoogwaardige medische zorg',
				'Herstellen in serene en pittoreske omgevingen',
				'Persoonlijke ondersteuning tijdens je verblijf',
			],
			cta: '..handel nu!',
			cta2: 'Handel Nu voor Medisch Toerisme',
		},
		{
			id: 'service-4',
			title: 'Hotelreservering',
			slug: 'hotel-reservation',
			description: 'Boek je verblijf in top-rated hotels die zijn afgestemd op je voorkeuren.',
			icon: images.reservation,
			content:
				'Vind en boek je ideale verblijf in top-rated hotels in Albanië. Of je nu de voorkeur geeft aan luxe accommodaties of gezellige boetiekhotels, we zorgen voor je comfort en tevredenheid. Onze reserveringsdiensten zijn afgestemd op jouw voorkeuren en budget.',
			whyUsTitle: 'Waarom bij ons boeken:',
			whyUsArr: ['Toegang tot exclusieve aanbiedingen', 'Persoonlijke aanbevelingen', 'Snelle en probleemloze boekingen'],
			cta: '...boek nu!',
			cta2: 'Boek Je Hotel Nu',
		},
		{
			id: 'service-5',
			title: 'Huur een Auto',
			slug: 'rent-car',
			description: 'Gemakkelijke en betaalbare autoverhuurdiensten voor je reizen.',
			icon: images.rentalCar,
			content:
				'Verken Albanië in je eigen tempo met onze gemakkelijke en betaalbare autoverhuurdiensten. Van stadsritjes tot avonturen op het platteland, onze vloot van betrouwbare voertuigen zorgt voor een soepele reis, waar je ook gaat.',
			whyUsTitle: 'Waarom een auto bij ons huren:',
			whyUsArr: ['Breed scala aan voertuigopties', 'Betaalbare tarieven', 'Eenvoudige ophaal- en inleverlocaties'],
			cta: '...huur nu!',
			cta2: 'Huur Je Auto Vandaag',
		},
	],
	arabic: [
		{
			id: 'service-1',
			title: 'باكجات الجولات',
			slug: 'tour-packages',
			description: 'استكشف الجولات المختارة التي تغطي أفضل الوجهات والتجارب.',
			icon: images.tourGuide,
			content:
				'استكشف الجولات المختارة التي تبرز أفضل ما في ألبانيا. من العجائب الطبيعية الخلابة إلى المعالم الثقافية، تم تصميم باكجات الجولات لدينا لتوفير تجارب لا تُنسى لجميع أنواع المسافرين. سواء كنت تبحث عن مغامرة، أو شغوفًا بالتاريخ، أو شخصًا يحب الاسترخاء على الشاطئ، لدينا شيء مميز لك.',
			whyUsTitle: 'لماذا تختارنا:',
			whyUsArr: ['مسارات مصممة بشكل احترافي', 'مرشدون سياحيون محليون ذوو معرفة', 'خيارات مرنة للعائلات، الأزواج، والمسافرين الفرديين'],
			cta: '..المزيد من الجولات',
			cta2: 'استكشف المزيد من الجولات',
		},
		{
			id: 'service-2',
			title: 'خدمات النقل',
			slug: 'city-transfer',
			description: 'نقل موثوق ومريح إلى المدينة لتلبية جميع احتياجات سفرك.',
			icon: images.transfer,
			content:
				'استمتع بنقل موثوق ومريح خلال مغامرتك في ألبانيا. تضمن خدمات النقل لدينا أن تسافر بسهولة، سواء كانت استقبالات من المطار، أو رحلات بين المدن، أو طرق مخصصة. نحن نولي الأولوية للسلامة والدقة، لذا يمكنك التركيز على الاستكشاف.',
			whyUsTitle: 'تشمل خدمات النقل لدينا:',
			whyUsArr: ['نقل من المطار إلى المدينة', 'اتصالات بين المدن', 'خيارات خاصة ومجموعة'],
			cta: '...المزيد من النقل',
			cta2: 'اكتشف المزيد من النقل',
		},
		{
			id: 'service-3',
			title: 'السياحة الطبية',
			slug: 'medical-tourism',
			description: 'احصل على أفضل خدمات الرعاية الصحية أثناء استكشاف وجهات جديدة.',
			icon: images.medicalTourism,
			content:
				'اجمع بين خدمات الرعاية الصحية الممتازة وجمال ألبانيا. تربطك باكجات السياحة الطبية لدينا بمقدمي الرعاية الصحية الرائدين مع منحك الفرصة لاستكشاف بلدنا الجميل. من منتجعات العافية إلى العلاجات المتخصصة، تعتبر ألبانيا وجهة مثالية للصحة والاسترخاء.',
			whyUsTitle: 'فوائد السياحة الطبية في ألبانيا:',
			whyUsArr: ['الوصول إلى رعاية طبية عالية الجودة وبأسعار معقولة', 'التعافي في أجواء هادئة وجميلة', 'دعم مخصص طوال إقامتك'],
			cta: '..تصرف الآن!',
			cta2: 'تصرف الآن للسياحة الطبية',
		},
		{
			id: 'service-4',
			title: 'حجز الفنادق',
			slug: 'hotel-reservation',
			description: 'احجز إقامتك في فنادق ذات تقييمات عالية تناسب تفضيلاتك.',
			icon: images.reservation,
			content:
				'ابحث واحجز إقامتك المثالية في فنادق ذات تقييمات عالية في ألبانيا. سواء كنت تفضل الإقامة الفاخرة أو الفنادق الصغيرة المريحة، نحن نضمن راحتك ورضاك. خدمات الحجز لدينا مصممة لتناسب تفضيلاتك وميزانيتك.',
			whyUsTitle: 'لماذا تحجز معنا:',
			whyUsArr: ['الوصول إلى عروض حصرية', 'توصيات مخصصة', 'حجوزات سريعة وبدون متاعب'],
			cta: '...احجز الآن!',
			cta2: 'احجز فندقك الآن',
		},
		{
			id: 'service-5',
			title: 'استئجار سيارة',
			slug: 'rent-car',
			description: 'خدمات تأجير سيارات مريحة وبأسعار معقولة لسفرك.',
			icon: images.rentalCar,
			content:
				'استكشف ألبانيا على طريقتك الخاصة مع خدمات تأجير السيارات المريحة وبأسعار معقولة. من القيادة في المدينة إلى مغامرات الريف، تضمن أسطولنا من المركبات الموثوقة رحلة سلسة أينما ذهبت.',
			whyUsTitle: 'لماذا تستأجر سيارة منا:',
			whyUsArr: ['مجموعة واسعة من خيارات المركبات', 'أسعار معقولة', 'مواقع استلام وتسليم سهلة'],
			cta: '...استأجر الآن!',
			cta2: 'استأجر سيارتك اليوم',
		},
	],
};
