export const images = {
	boutique: '/png/boutique.png',
	culture: '/png/culture.png',
	family: '/png/family.png',
	hiddenGems: '/png/hidden-gems.png',
	hiking: '/png/hiking.png',
	hotel: '/png/hotel.png',
	reservation: '/png/reservation.png',
	market: '/png/market.png',
	nightlife: '/png/nightlife.png',
	restaurant: '/png/restaurant.png',
	sightseeing: '/png/sightseeing.png',
	transfer: '/png/transfer.png',
	cratour: '/png/cratour.png',
	phoneCall: '/png/phone-call.png',
	map: '/png/map.png',
	medicalTourism: '/png/medical-tourism.png',
	tourGuide: '/png/tour-guide.png',
	rentalCar: '/png/rental-car.png',
};
